package com.landstack.entity;

public enum ApplicationStatus {
    SUBMITTED,
    UNDER_REVIEW,
    ASSIGNED_TO_OFFICER,
    OFFICER_PROCESSING,
    PENDING_DOCUMENTS,
    DOCUMENT_VERIFICATION,
    FIELD_VERIFICATION,
    INSPECTION_COMPLETED,
    REPORT_SUBMITTED,
    SUBMITTED_FOR_SUPERVISOR_REVIEW,
    FORWARDED_TO_AUTHORITY,
    CLARIFICATION_REQUIRED,
    RETURNED_TO_OFFICER,
    CORRECTION_REQUIRED,
    FURTHER_INSPECTION_REQUIRED,
    READY_FOR_APPROVAL,
    VERIFIED,
    SUPERVISOR_REVIEW,
    APPROVED,
    REJECTED,
    ESCALATED,
    COMPLETED
}
